default : &DEFAULT


    seed: 2024 #42
    #dtype: torch.float32
    run_name: ettm1
    test: False
    cfg: None
    data:
        dataset: "ettm1"
        split_ratio: [0.6, 0.2, 0.2]    # train, val, test
        feature_dim: 7
        seq_len:  336
        pred_len: 192 
        data_path: 'data/ETT-small/ETTm1.csv'
        scale: True    # normalise data
        target: 'OT'   # target column
        features: 'M'
        timeenc: 1
        freq: 'm'
        batch_size: 64 
        test_batch_size: 32
        shuffle: True
        drop_last: True

    train:
        device: "cuda:0"
        optimizer: Adam
        epochs: 100
        lr: 0.001
        patience: 10

    model:
        hidden_dim: 512
        n_emb: 1
        n_heads: 8
        attn_dropout: 0.1
        mlp_ratio: 1
        n_depth: 1
    use_cond: True
        
    diff:
        noise_type: "t_phi"
        beta_schedule: quad
        beta_start: 0.0001
        beta_end: 0.1
        timesteps: 100
        model_type: "CN_Diff" 
        n_copies_to_test: 10
        
        
